spring.application.name=demo-app
management.endpoints.web.exposure.include=*
# How to exclude or include endpoints
#management.endpoints.web.exposure.include=health,info
#management.endpoints.web.exposure.exclude=health,info
management.info.env.enabled=true

spring.security.user.name=carrington96
spring.security.user.password=muleya


info.app.name=Vroom hive Application
info.app.description=Car Marketplace API
info.app.version=1.0.0-beta

info.dev.name=Carrington Muleya
info.dev.description=Full Stack Developer
info.dev.year=10th-year
