spring.application.name=demo-app
management.endpoints.web.exposure.include=*
#management.endpoints.web.exposure.include=health,info
management.info.env.enabled=true

info.app.name=Vroomhive Application
info.app.description=Car Marketplace API
info.app.version=1.0.0-beta

info.dev.name=Carrington Muleya
info.dev.description=Full Stack Developer
info.dev.year=10th-year
